name: CI
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '1.17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "jukeboxmc-releases",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_SECRET }}"
            },
            {
              "id": "jukeboxmc-snapshots",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_SECRET }}"
            }]
      - name: Publish with Maven
        run: mvn -B package deploy --file pom.xml
        env:
          MAVEN_NAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_SECRET: ${{ secrets.REPO_SECRET }}