name: CI
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '1.17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "jukeboxmc-releases",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_SECRET }}"
            },
            {
              "id": "jukeboxmc-snapshots",
              "username": "${{ secrets.REPO_USERNAME }}",
              "password": "${{ secrets.REPO_SECRET }}"
            }]
      - name: Publish with Maven
        run: mvn -B package deploy --file pom.xml
        env:
          MAVEN_NAME: ${{ secrets.REPO_USERNAME }}
          MAVEN_SECRET: ${{ secrets.REPO_SECRET }}
      - name: Set environment variables
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "BUILD_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV
      - name: Create Prerelease
        if: ${{ endsWith(env.VERSION, '-SNAPSHOT') }}
        id: create_prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pre-${{ github.run_number }}
          release_name: JukeboxMC pre-${{ github.run_number }}
          draft: false
          prerelease: true
      - name: Create Release
        if: ${{ !endsWith(env.VERSION, '-SNAPSHOT') }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: JukeboxMC ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload JukeboxMC as Prerelease
        if: ${{ endsWith(env.VERSION, '-SNAPSHOT') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_prerelease.outputs.upload_url }}
          asset_path: target/${{ env.BUILD_NAME }}.jar
          asset_name: ${{ env.BUILD_NAME }}.jar
          asset_content_type: application/java-archive
      - name: Upload JukeboxMC as Release
        if: ${{ !endsWith(env.VERSION, '-SNAPSHOT') }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${{ env.BUILD_NAME }}.jar
          asset_name: ${{ env.BUILD_NAME }}.jar
          asset_content_type: application/java-archive