name: Prerelease Java CI with Maven

on:
  push:
    branches: [master]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '1.17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn install
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: pre-${{ github.run_number }}
          release_name: JukeboxMC pre-${{ github.run_number }}
          draft: false
          prerelease: true
      - name: Set environment variables
        run: |
          echo "GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
          echo "ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          echo "BUILD_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV
      - name: Upload JukeboxMC to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${{ env.BUILD_NAME }}.jar
          asset_name: ${{ env.BUILD_NAME }}.jar
          asset_content_type: application/java-archive
      - name: Nexus Repo Publish
        uses: ./
        with:
          serverUrl: http://jukeboxmc.eu:8081
          username: ${{ secrets.NEXUS_REPO_USERNAME }}
          password: ${{ secrets.NEXUS_REPO_PASSWORD }}
          format: maven2
          repository: maven-snapshots
          coordinates: groupId=${{ env.GROUP_ID }} artifactId=${{ env.ARTIFACT_ID }} version=${{ env.VERSION }}
          assets: extension=jar
          filename: ./target/${{ env.BUILD_NAME }}.jar